// <auto-generated />
using System;
using BtlWebNangCao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BtlWebNangCao.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BtlWebNangCao.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("BtlWebNangCao.Models.PhongChat", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"), 1L, 1);

                    b.Property<bool>("LaCongKhai")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("PhongChats");
                });

            modelBuilder.Entity("BtlWebNangCao.Models.ThanhVienPhong", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTroPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung", "MaPhong");

                    b.HasIndex("MaPhong");

                    b.ToTable("ThanhVienPhongs");
                });

            modelBuilder.Entity("BtlWebNangCao.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"), 1L, 1);

                    b.Property<int>("MaNguoiGui")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaPhong");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("BtlWebNangCao.Models.PhongChat", b =>
                {
                    b.HasOne("BtlWebNangCao.Models.NguoiDung", "NguoiTao")
                        .WithMany("DanhSachPhongTao")
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("BtlWebNangCao.Models.ThanhVienPhong", b =>
                {
                    b.HasOne("BtlWebNangCao.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachPhongThamGia")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BtlWebNangCao.Models.PhongChat", "PhongChat")
                        .WithMany("DanhSachThanhVien")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("PhongChat");
                });

            modelBuilder.Entity("BtlWebNangCao.Models.TinNhan", b =>
                {
                    b.HasOne("BtlWebNangCao.Models.NguoiDung", "NguoiGui")
                        .WithMany("DanhSachTinNhan")
                        .HasForeignKey("MaNguoiGui")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BtlWebNangCao.Models.PhongChat", "PhongChat")
                        .WithMany("DanhSachTinNhan")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("PhongChat");
                });

            modelBuilder.Entity("BtlWebNangCao.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhSachPhongTao");

                    b.Navigation("DanhSachPhongThamGia");

                    b.Navigation("DanhSachTinNhan");
                });

            modelBuilder.Entity("BtlWebNangCao.Models.PhongChat", b =>
                {
                    b.Navigation("DanhSachThanhVien");

                    b.Navigation("DanhSachTinNhan");
                });
#pragma warning restore 612, 618
        }
    }
}
